#include <iostream>
#include <stdlib.h>
#include <time.h>

using namespace std ;

int main()
{
int num; int g;
srand(time(0)); 
cout << "               NUMBER  GUESSING  GAME " << endl ;
cout << "\n" ;
cout << "Guess the number generated by the computer." <<endl ;
cout << "HINT:  The number ranges from 1 to 100! " << endl ;

num = rand()%100 + 1;

cout << "Enter your guess :" << endl;
cin >> g ;
while(num!=g)
{
    if (num>g)
    {  cout << "Your guess is low" << endl ;

    } 
  else {
    cout << "Your guess is high " << endl ;

  }

 cout << "Guess again" << endl ;
 cin >> g ;

}
cout << "CORRECT ! " << endl ;
cout << "The generated number is : " << num ;

return 0;
}